#3102: Create a bug report template
Chaste/Chaste pull request #30
Opened 2022-12-08 11:26 UTC by kwabenantim

2022-12-08 11:33 UTC, MauriceHendrix approved these changes
looks good to me!

2022-12-08 11:35 UTC, mirams commented on .github/ISSUE_TEMPLATE/bug_report.md
> + * Relevant Chaste dependency versions e.g. PETSc, Boost, Sundials etc.
You could ask for the output of TestChasteBuildInfo.hpp here.

2022-12-08 11:41 UTC, mirams requested changes
You could ask for the output of `TestChasteBuildInfo.hpp` which should give most of the info on dependencies and build type etc.

2022-12-08 13:32 UTC, kwabenantim commented
> You could ask for the output of `TestChasteBuildInfo.hpp` which should give most of the info on dependencies and build type etc.

Thanks @mirams. I've added some information about getting the output from `TestChasteBuildInfo.hpp` .

2022-12-08 13:41 UTC, mirams commented
Yeah, you don't want output on failure though, you want all the output when it passes as that will show the dependency versions

2022-12-08 14:56 UTC, kwabenantim commented
> Yeah, you don't want output on failure though, you want all the output when it passes as that will show the dependency versions

Thanks. It's now `ctest -V -R TestChasteBuildInfo` without the ~~`--output-on-failure`~~.

2022-12-13 11:20 UTC, mirams approved these changes

2022-12-13 11:35 UTC, merged