Added comments about build options
Chaste/Chaste pull request #94
Opened 2023-04-04 14:54 UTC by MauriceHendrix

2023-06-30 09:33 UTC, mirams requested changes

2023-06-30 09:33 UTC, mirams commented on global/test/TestCommandLineArguments.hpp
> + *  For example:
This `CommandLineArguments` is to do with passing in arguments to compiled executables. scons used to have an option to "build and run with these command line arguments to the test/executable" but I guess that would now be something to do with `ctest` if that can actually do it?

2023-06-30 09:37 UTC, MauriceHendrix commented on global/test/TestCommandLineArguments.hpp
> + *  For example:
Probably, but worth checking with @fcooper8472

2023-08-15 10:17 UTC, mirams commented
For this to be sorted we want to give advice on how to pass command line arguments to a test at the time you write `ctest TestBlah....` 

Some stackoverflow here that looks very complicated! https://stackoverflow.com/questions/28812533/how-to-pass-command-line-arguments-in-ctest-at-runtime

2024-01-23 09:54 UTC, mirams commented on apps/texttest/weekly/MeshConvert/Tutorial.wiki
> +`make <target name> -DCMAKE_BUILD_TYPE=Release` where is your build tareget e.g. Chaste, or a user project such as ApPredict
```suggestion
`make <target name> -DCMAKE_BUILD_TYPE=Release` where is your build target e.g. Chaste, or a user project such as ApPredict
```

2025-09-30 09:35 UTC, mirams approved these changes

2025-09-30 09:35 UTC, merged